### ISSUE TITLE
Set it up, but no task appears.

### ISSUE THREAD

**Issue by LordVlad-Neutral** [CitizenPrayer/Habitica-Piggy-Bank#1]
Documentation would be great... But I've already set up a lot of scripts... I expected to have a "Piggy Bank" task or two appear but no, nothing. I had high hopes for an automatic banking system for Habitica... Well, I hope we'll find out if there is ever an answer.

**Comment by 0xCyberFortress** [comment]
Hey LordVlad!! I'm sorry I'm just now getting to this. I'm by no means a developer and had to have someone else help me even throw this together. I even forgot it was here until I myself googled "Habitica piggy bank" and saw my own name. LOL!! I'll see if I can continue this project again.

**Comment by LordVlad-Neutral** [comment]
Ok, no worries, I'm myself not much of a coder, but I'll keep an eye on this. I've been craving an automatic, or at least easy to use banking system since scriptabit fell into disrepair, few years ago.

**Comment by 0xCyberFortress** [comment]
I understand. If you want to have a look at how this script will look once I'm done with it, have a look at the project description. With that said, I'll go ahead and close this issue as a known bug :)
